final List<String> electives = [
  "Accounting",
  "Agricultural Management Practices",
  "Agricultural Sciences",
  "Agricultural Technology",
  "Associated Board Of Royal ...",
  "Business Studies",
  "Civil Technology",
  "Computer Applications Technology",
  "Consumer Studies",
  "Dance Studies",
  "Design",
  "Dramatic Arts",
  "Economics",
  "Electrical Technology",
  "Engineering Graphics and Design",
  "Equine Studies",
  "Geography",
  "History",
  "Hospitality Studies",
  "Information Technology",
  "Italian (Second Additional Language)",
  "Latin (Second Additional Language)",
  "Life Sciences",
  "Maritime Economics",
  "Mechanical Technology",
  "Music",
  "Nautical Science",
  "Physical Sciences",
  "Religion Studies",
  "Sport and Exercise Science",
  "Technical Mathematics",
  "Technical Sciences",
  "Tourism",
  "Trinity College of London ...",
  "UNISA Practical Music",
  "Visual Arts",
  "None",
];

final List<String> homeLanguages = [
  "Afrikaans",
  "English",
  "isiNdebele",
  "isiXhosa",
  "isiZulu",
  "Sepedi",
  "Sesotho",
  "Setswana",
  "SiSwati",
  "Tshivenda",
  "Xitsonga",
  "None"
];

final List<String> firstAdditionalLanguages = [
  "Afrikaans",
  "English",
  "isiNdebele",
  "isiXhosa",
  "isiZulu",
  "Sepedi",
  "Sesotho",
  "Setswana",
  "SiSwati",
  "Tshivenda",
  "Xitsonga",
];

final List<String> secondAdditionalLanguages = [
  "English ",
  "Afrikaans ",
  "isiNdebele ",
  "isiXhosa ",
  "isiZulu ",
  "Sepedi (Northern Sotho) ",
  "Sesotho (Southern Sotho) ",
  "Setswana (Tswana) ",
  "SiSwati (Swazi) ",
  "Tshivenda ",
  "Xitsonga ",
  "Arabic ",
  "French ",
  "German ",
  "Gujarati ",
  "Hebrew ",
  "Hindi ",
  "Italian ",
  "Latin ",
  "Mandarin ",
  "Modern Greek ",
  "None"
];

final List<String> mathematics = [
  "Mathematics",
  "Mathematical Literacy",
  "Technichal Mathematics",
];
